[[pages]]
path = "/"
screenshotTimestamp = "2026-03-23T13:55:52Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/48db8c87-1b6e-44c3-9793-8201301190e0/2973b18a-fcdb-4c6a-abee-9baf1626b74e/aYUXgxH"
